apiVersion: v1
kind: Service
metadata:
    name: nodeapp
    namespace: demo
    labels:
        app: nodeapp
spec:
    type: ClusterIP
    ports:
    - port: 8080
      protocol: TCP
    selector:
        app: nodeapp
